database:
  driver: sqlite
  name: data.db
  log:
    store: false
    level: INFO # SILENT, ERROR, WARN, INFO
server:
  log:
    store: false
    level: INFO # PANIC, FATAL, ERROR, WARN, INFO, DEBUG, TRACE
gin:
  log:
    store: false
    level: debug # debug, release, test